"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
https://github.com/grpc/grpc/blob/b8a04ac/examples/protos/route_guide.proto"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Point(google.protobuf.message.Message):
    """Points are represented as latitude-longitude pairs in the E7 representation
    (degrees multiplied by 10**7 and rounded to the nearest integer).
    Latitudes should be in the range +/- 90 degrees and longitude should be in
    the range +/- 180 degrees (inclusive).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    latitude: builtins.int
    longitude: builtins.int
    def __init__(
        self,
        *,
        latitude: builtins.int = ...,
        longitude: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["latitude", b"latitude", "longitude", b"longitude"]) -> None: ...

global___Point = Point

@typing.final
class Rectangle(google.protobuf.message.Message):
    """A latitude-longitude rectangle, represented as two diagonally opposite
    points "lo" and "hi".
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LO_FIELD_NUMBER: builtins.int
    HI_FIELD_NUMBER: builtins.int
    @property
    def lo(self) -> global___Point:
        """One corner of the rectangle."""

    @property
    def hi(self) -> global___Point:
        """The other corner of the rectangle."""

    def __init__(
        self,
        *,
        lo: global___Point | None = ...,
        hi: global___Point | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["hi", b"hi", "lo", b"lo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["hi", b"hi", "lo", b"lo"]) -> None: ...

global___Rectangle = Rectangle

@typing.final
class Feature(google.protobuf.message.Message):
    """A feature names something at a given point.

    If a feature could not be named, the name is empty.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the feature."""
    @property
    def location(self) -> global___Point:
        """The point where the feature is detected."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        location: global___Point | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["location", b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["location", b"location", "name", b"name"]) -> None: ...

global___Feature = Feature

@typing.final
class RouteNote(google.protobuf.message.Message):
    """A RouteNote is a message sent while at a given point."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOCATION_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    message: builtins.str
    """The message to be sent."""
    @property
    def location(self) -> global___Point:
        """The location from which the message is sent."""

    def __init__(
        self,
        *,
        location: global___Point | None = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["location", b"location"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["location", b"location", "message", b"message"]) -> None: ...

global___RouteNote = RouteNote

@typing.final
class RouteSummary(google.protobuf.message.Message):
    """A RouteSummary is received in response to a RecordRoute rpc.

    It contains the number of individual points received, the number of
    detected features, and the total distance covered as the cumulative sum of
    the distance between each point.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POINT_COUNT_FIELD_NUMBER: builtins.int
    FEATURE_COUNT_FIELD_NUMBER: builtins.int
    DISTANCE_FIELD_NUMBER: builtins.int
    ELAPSED_TIME_FIELD_NUMBER: builtins.int
    point_count: builtins.int
    """The number of points received."""
    feature_count: builtins.int
    """The number of known features passed while traversing the route."""
    distance: builtins.int
    """The distance covered in metres."""
    elapsed_time: builtins.int
    """The duration of the traversal in seconds."""
    def __init__(
        self,
        *,
        point_count: builtins.int = ...,
        feature_count: builtins.int = ...,
        distance: builtins.int = ...,
        elapsed_time: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["distance", b"distance", "elapsed_time", b"elapsed_time", "feature_count", b"feature_count", "point_count", b"point_count"]) -> None: ...

global___RouteSummary = RouteSummary
